name: Daily Task Reminder

on:
  schedule:
    - cron: '32 16 * * *'  # 01:02 AM IST (every day)
  workflow_dispatch:

jobs:
  run-task-reminder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the task reminder script
        run: python task_reminder.py
